### ISSUE TITLE
session_start() in example/ipn-example.php ?

### ISSUE THREAD

**Issue by henkealg** [PaysonAktiebolag/api-integration-php#8]
Thanks for a good and usable library.
Is there a reason for setting a session as a part of the ipn handling process in the examples.
It does not seem to ad to the library functions. Although our inplementation works without the session I just want to make sure that this is not mandatory for the library to handle ipn calls.

**Comment by PaysonAB** [comment]
Hi,

No, you are not required to use session_start()

Best regards
Payson
